### ISSUE TITLE
Unmatched size of prostate masks

### ISSUE THREAD

**Issue by hiyuhan** [rcuocolo/PROSTATEx_masks#10]
Hi, very nice work. I found there are some unmatched size between 'mask_prostate', 'mask_pz', 'mask_tz' and raw T2 dicoms from ProstateX challenge. Would you please check? Part of the files is listed as following:
error size: ProstateX-0102 pz
error size: ProstateX-0102 tz
error size: ProstateX-0141 pz
error size: ProstateX-0141 tz
error size: ProstateX-0160 pz
error size: ProstateX-0160 tz
error size: ProstateX-0165 pz
error size: ProstateX-0165 tz
error size: ProstateX-0166 pz
error size: ProstateX-0166 tz
error size: ProstateX-0168 pz
error size: ProstateX-0168 tz
error size: ProstateX-0173 pz
error size: ProstateX-0173 tz
error size: ProstateX-0181 pz
error size: ProstateX-0181 tz
error size: ProstateX-0191 pz
error size: ProstateX-0191 tz
error size: ProstateX-0197 pz
error size: ProstateX-0197 tz
error size: ProstateX-0199 pz
error size: ProstateX-0199 tz
error size: ProstateX-0201 pz
error size: ProstateX-0201 tz
error size: ProstateX-0202 pz
error size: ProstateX-0202 tz
error size: ProstateX-0203 pz
error size: ProstateX-0203 tz

**Comment by rcuocolo** [comment]
I have checked the first 2 cases (as a sample). The issue is simply that multiple axial T2 sequences are available, and the anatomical masks in these were not taken on the same images as the lesion masks. This is already reflected in the image list CSV files in each folder. These specify the correct T2 sequence to use for each mask (lesion or anatomical). I understand this is not ideal, but the two processes were conducted in separate occasions and different files were employed.
Please check you are referencing the correct image list for the mask set.

**Comment by hiyuhan** [comment]
Thanks for the fast reply. I have checked the files and you are right. May I ask how to choose between the different T2 images in a single patient scan, like for zonal segmentation. Or I am confused on why there can be two similar T2s.

**Comment by rcuocolo** [comment]
The sequences were repeated in the dataset for unknown reasons. For us, the choice was essentially due to chance. In some cases there might be artifacts (e.g., patient movement) that require a new acquisition of a series, but the images used for the segmentation process were all considered viable for the task at hand. In one of the papers we report the exclusion of 1 case for artifacts on the ADC map (for the purpose of lesion segmentation, T2 images were fine for gland/zonal segmentation).

**Comment by hiyuhan** [comment]
Very clear. I shall check your papers. Thanks a lot.
