### ISSUE TITLE
Submit to TCIA?

### ISSUE THREAD

**Issue by fedorov** [rcuocolo/PROSTATEx_masks#15]
Note that TCIA, which holds the PROSTATEx collection, has a process that allows users to submit analysis results, see https://www.cancerimagingarchive.net/analysis-results/. This way it would be easier to discover your dataset, you would get a DOI that can be cited, and masks will be easy to access and visualize along with the original images. Would be great if you could consider submitting this dataset to TCIA.

**Comment by rcuocolo** [comment]
Thank you for the suggestion. I will try submitting the dataset to TCIA as soon as possible, even though there are some unsolved issues with the ADC masks for the DICOM images. Maybe I could upload the masks for the NiFTI-converted exams as well, as done for this site.

**Comment by rcuocolo** [comment]
Unfortunately the issue (#9) persists. I would like to submit masks that are compatible with the DICOM files on TCIA rather than requiring conversion to NIFTI. As soon as I am able to solve this issue I will proceed to the upload.
Do you know if TCIA allows updating or editing the files easily or does the product need to be in a definitive state?

**Comment by rcuocolo** [comment]
I proposed the submission today. If it is approved I will upload the same files to the TCIA as presented here.

**Comment by fedorov** [comment]
If #9 persists, and it is not possible to overlay those segmentations with the DICOM images using tools like 3D Slicer, then I don't think it will be accepted by TCIA.

**Comment by rcuocolo** [comment]
I imagine the issue is solvable, but would require too much time for me to tackle it at the time. Providing NIFTI images and masks effectively avoids the problem altogether and allows for the correct use of the masks (checked both on 3D Slicer and ITKSnap). Transposing masks for use on the original DICOM files is not part of my usual workflow and I underestimated this aspect at the time of first processing.
In my submission to TCIA I specified all files will be in NIFTI format, let's see what they answer. Anyhow, the most important thing for me is having made a usable dataset available. I am only sorry for early cloners/users who might have to reimplement the dataset in its current form. Hopefully they have been made aware of the issues by the subsequent release version updates.
