### ISSUE TITLE
A question about the marked lesion mask

### ISSUE THREAD

**Issue by serllad** [rcuocolo/PROSTATEx_masks#2]
Hello, I'm sorry to bother you,I have downloaded the mask label of the lesion in the ProStatex dataset you uploaded a few days ago. Thank you very much for your work.
But I have a question: in PROSTATEx_masks - master/Files/lesions/Masks/T2 / ProstateX - 0000 - Finding1 - t2_tse_tra_ROI. Nii. Gz file Prostatex-0000 patients have only one lesion, and the label in the data set is on the slice numbered 9. I see the mask you made on the label 8, 9, 10 and 11 all have lesions, but 11 is obviously larger than 10 and the position is further to the right
I would be very grateful if you could give me your reply. I wish you a successful scientific research

**Comment by rcuocolo** [comment]
Hello, thank you for your interest in this data repository.
I checked the lesion you mentioned (finding 1 in PROSTATEx-0000.) The mask on the T2w images looks fine, it delineates the area of hypointensity identified by the original dataset's lesion coordinates. The ROI areas on each slice are correctly attached to the contiguous slices (i.e., there is no gap within the lesion mask). The lesion morphology can be quite variable between different prostate cancer patients. For example, this patient had a fairly aggressive lesion (ISUP score 3, Gleason Score 4+3) with some irregularity in its margins (and may be suspect for extracapsular extension due to its location).
Please let me know if there are any further issues you wish to have clarified, or we can close this thread.
