### ISSUE TITLE
Multi-parametric lesion segmentation

### ISSUE THREAD

**Issue by a6225301** [rcuocolo/PROSTATEx_masks#3]
Hi, thank you for providing this perferct repository. Now,  I want to conduct the Multi-parametric (ADC, T2) lesion segmentation task. And I have faced two main problems, hope  you can help me.

1. Since the resolution of ADC and T2 is not the same, do you have any registration method to make position consistent of different modalities.
2. The annotated mask of different modalities (ADC, T2) is not in the same slice, if we assume that I have done the registration of those two modalities, which annotated mask of the modality should be the final ground truth for the leison segmentation? ( ADC? T2? By voting or average those two masks ?) 

Hope you can help me.

**Comment by rcuocolo** [comment]
Hello, thank you for your interest in our work.
Regarding point 1, the lesions were manually segmented on both T2w and ADC images, we did not use any registration software to transpose ROIs. I would advise using these masks rather than only one and registering it to the other sequence, for the reasons you state (different resolution) and due to minor geometrical differences and possible artifacts in DWI/ADC. The ADC mask can be also used for DWI (they have the same geometry), but as we explain in the paper (hope it comes out soon) the PROSTATEx dataset DWI does not have a high b value volume (max b = 800), therefore it would be better to only use ADC maps.
Similarly, for point 2, I would use the appropriate mask for each lesion to avoid any issues. If the case-finding ID matches, the masks refer to the same lesion on both MRI sequences. Averaging or registering one mask to the other would be a suboptimal solution. Lesion location was visually confirmed by radiologists (including myself) on each sequence prior to manual annotation.
I hope to have answered your questions, please let me know if you have any remaining doubts. Also, please signal any eventual issues with the masks in and of themselves and/or feel free to make a pull request with any improved file.

**Comment by a6225301** [comment]
Thanks for your help. And it would be better if you can add more data helper such as dataset from the link : http://i2cvb.github.io/ .  It is aslo a public prostate cancer dataset which is usually used.

**Comment by rcuocolo** [comment]
We are looking for additional dataset, however the one you linked does not seem to focus on clinically significant prostate cancer, but all prostate cancer. This is of limited interest as MRI already has a fairly high negative predictive power. The challenge in prostate MRI is in distinguishing clinically significant lesions from non significant (e.g. Gleason Score 3+3) ones. Gleason score is not the only factor influencing lesion significance but is the most commonly used proxy.
Unfortunately, I have found little to none reasonably-sized datasets including Gleason score or other useful clinical data. For example, PROSTATEx itself is missing PSA and age, which are other clinical features known to be useful. This is part of the reason we decided to improve PROSTATEx in order to extract maximum value from the available data.
